# Generated by Django 5.2.5 on 2025-08-19 20:59

import oficina.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la oficina')),
                ('nombre_corto', models.SlugField(help_text='Código corto único (ej: PER, ADM, etc.)', max_length=10, unique=True, validators=[oficina.models.validate_nombre_corto], verbose_name='Id Corto')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
            },
        ),
    ]
